package projects;
import java.util.Scanner;
import java.util.Random;

public class Having_Fun {
    public static void main(String[] args) {

        /*  CREDITS: Ideas were generated by AI, all code is written by myself, option Z is courtesy of A
         *   ________________
         *  |   ---_  _---   |
         *  |  -----  -----  |
         *  |    -______-    |
         *   ________________
        */
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        char charInput;
        int generatedNumberEyes;
        int generatedNumberMouths;
        int mazeWallOrFloor;
        int eightBallAnswer;
        int randomSauces;
        int randomBasicIngredients;
        int randomBasicIngredients2;
        int randomMeasurements;
        int randomMeasurements2;
        int randomMeasurements3;


        System.out.print("Pick A, B or C: ");
        charInput = scanner.next().charAt(0); //https://stackoverflow.com/questions/13942701/take-a-char-input-from-the-scanner

        switch(charInput){
            case 'A':
                generatedNumberEyes = random.nextInt(0, 6); // Second val is exclusive
                generatedNumberMouths = random.nextInt(0, 4);

                String[] eyes = {"0 0", "T T", "@ @", "* *", "^ ^", "¬ ¬"}; //https://www.w3schools.com/java/java_arrays.asp
                String[] mouths = {"___", " ~", "---", ">"};

                System.out.println(eyes[generatedNumberEyes]);
                System.out.println(mouths[generatedNumberMouths]);
                break; //https://www.reddit.com/r/CodingHelp/comments/r8vllw/whats_the_difference_between_break_continue_and/

            case 'B':
                // # = walls . = floor
                for (int i = 0; i < 3; i++){ //https://www.w3schools.com/java/java_for_loop.asp
                    System.out.println();
                    for(int j = 0; j < 5; j++){

                        mazeWallOrFloor = random.nextInt(0, 2);
                        if(mazeWallOrFloor == 0){
                            System.out.print("#");
                        }else if(mazeWallOrFloor == 1){
                            System.out.print(".");
                        }else{
                            System.out.println("Something went wrong lad...");
                        }
                    }
                    if(i == 3){
                        return; //Figure out how to exit the loop and stop running the code
                    }
                }
            case 'C':
                scanner.nextLine(); // Clear the buffer to remove the \n
                System.out.print("What do you wish to ask the all mighty 8ball: ");
                scanner.nextLine();

                String[] eightBall = {"Yes", "No", "Absolutely Not", "Maybe?", "The day is in your hands", "Honestly? I dont know"};
                eightBallAnswer = random.nextInt(0, 6);

                System.out.println(eightBall[eightBallAnswer]);
                break;

            case 'Z':
                //Recipe generator
                String[] sauces = {"Ketchup", "Vanilla Extract", "Pesto", "Chili Sauce"};
                String[] basicIngredients = {"Flour", "Sugar", "Eggs", "Butter", "Yeast", "Baking soda"};
                String[] measurements = {"500g", "5g", "2", "150g", "50g"};
                randomSauces = random.nextInt(0, 4);
                randomBasicIngredients = random.nextInt(0, 6);
                randomBasicIngredients2 = random.nextInt(0, 6);
                randomMeasurements = random.nextInt(0, 5);
                randomMeasurements2 = random.nextInt(0, 5);
                randomMeasurements3 = random.nextInt(0, 5);

                System.out.println(measurements[randomMeasurements] + " " + basicIngredients[randomBasicIngredients] + " " +
                        measurements[randomMeasurements2] + " " + basicIngredients[randomBasicIngredients2] + " "
                        + measurements[randomMeasurements3] + " " + sauces[randomSauces]);
                System.out.println("\n Enjoy :D");
        }
        scanner.close();
    }
}
